sample_rate: 16000
max_epochs: 10
log_every_n_steps: 10
val_check_interval: 500
profiler: "simple"
model_type: 'protonet'
logger: "wandb"
wand_project_name: "wimu-agorski-okrupa"
model_output_path: "models/irmas"
